from Bio import Seq
from Bio import SeqIO

s1 = ("GCTAGCGCCGAACAGCTCAAGTTCGTATTTAACGCCGTTCGATACTCAGACCGCAGCGCTGGAACCACCCGTTTTCTAGGTACGTGCATACCGGGTGGGCGGCTAGCAGTACGAGCTTAGGTTGCCCTGGAACCACTGGTGAGATACAGAGTTGGCCCCCATACTGGACCCCACTCATCGGTTGCCAGGGCGTCAGCAGGCCGCTTCCATACGTCGCTGTCCGGTAACGCGCCCCGACTGGTCAGACAATAGGACCGGTGTGCCCATATGTCATTCAGACTGAACTCTTGGCATTATGCAATACAACGTGCTGGCACGCGATTGAATATGAGATAGAAGAACTGTCCTCGCCTAGTGTGATAAGGTCATCACAAGGTAGGTCACTCACGGTTAAGGACGCGCCGAATCGTTACTCTTTAGAACTGGAAGTGACTGTAGAAGCATAGAGTATGATTCCCATCTACAGGGCGCCTGCCGTATTGAGTGTTCTTCGATCCTGTTCTCAAGATGCTGCCGTCAATATAACGTAGAAAGCAACCCGCCCTCTGACTTTTGCTTGCCTGACAAAAACGCCCTCAGCAAAAGCGGCATCCACGCTCCTTCGGCATAGAAGGATGAACCGACCGGACTACATACCTCCGCGAGGGGGTGCTCACACAGCCATGCTTGCTCCTCCGTGACTAGGCGAGTATTACACGTACTTAGGTACAAGGGGGGCTCTGACACCCGCTACTCCGATCTTAAGAAGCAGCTAAGTATTTAGAGGGCGTGGACTCCCGGTGGGCCAAGCGCCCTGTGGTGGGCACGGGGTTCCTGTGTTCGTTGAACACTCAATCTGGCCTCGGTTTGGGTCCACATTCGTATCCAAATTGTGGTTTTGCTACAGTCCTTAAGACTCTATT")

s2 = ("CCCGCCGTTGACCAGTTCAAGTTCGCACCTAACGCAATCTGATACTCAGATCGCGGCGGTGGGCCCACTCATGCTGTCGATACATGTATGACGAATGGGGGGATAGTATGAAACGCCTAGGCTGCCTTGGAAGAACTGGCAAGGCTCACACTTGATCCTCATTTTGACTCCCGTTCGGCGAATGCCAGGGCGTCATTGGGCTGGCCCCTGAGATCGCTGTCCATTGGCGCCCCCAGATCCGTCACACAATAGGACCGGCATTCCCGTACGTCCTTCAGCCCTATTTCCTATTTATATACAATCTTATGTGCTAGTAAATGCCTGGATGAGAGCAAAAGGAGCTATCCCCGTGCAGTGTTATGAGGCGATCATGGGACAGGGCACGTTCATTTTAAGTCACGTAGAACCGCTACTCTTTCGGGCCAAGGGCGATTGTGGAAGCATGGTGTGCGGTCTCCGTCTACAGGGAGCCCGTCATGTTGAGTGTTTTTCGATCCTATTCTCAAGATGTTGTCTCCAATATGTCGTGCATAGGGTTCCACCCTCAGTACCTTGCTTACCTGACGAAAGTGTTCCCAGCAAAAGCAGCATGTGCGCTCCTCCGGAATATAAGGGTGAACTGACCAAGCCACATCCCGCCGCGAAGAGATGTTCATACGATCATACTCGTCCCTACGTGACTAAACTGGCACTGCACGTACCTAAGGGCAAGGCCGGCTCTGACACCCGCTACTCCGATCATAGGAGGCAACTAAGCTTGTGGAGGGCACGGATTTCCTGTCGGCCGATCGTCCTCCGCTGGGCTTGGACCTCTTGTGTTCAATAAACGCCCGATCTGGCCCCGGTTTGAATCTACACTTGAATTCAAACTGTCGTTTAGCTACGGCCCCTAAGAGTCTACT" )
def problem(s1, s2):
    transitions = set([('A', 'G'), ('G', 'A'), ('C', 'T'), ('T', 'C')])
    ratio = {True: 0.0, False: 0.0}
    for p in zip(s1, s2):
        if p[0] != p[1]:
            ratio[p in transitions] += 1
    return ratio[True] / ratio[False]


if __name__ == '__main__':
    import doctest
    from os.path import dirname
    #from .util import parse_fasta

    doctest.testmod()

    handle = open("C://Users//willi//Downloads//rosalind_tran.txt", "r")
    #dataset = (SeqIO.parse(handle, "fasta"))
    #s1, s2 = dataset.values()
    print (problem(s1, s2))
