s = "CGCCCAACTGTCAACTGTACCAACTGTTGCAACTGTCAACTGTCAACTGTACCAACTGTCCAACTGTTGACAACTGTCAACTGTACCAACTGTAACAACTGTCAACTGTACAACTGTCTTGTCAACTGTTTCCAACTGTTCAACTGTTCAACTGTATACGCAACTGTTGGCCAACTGTACCAACTGTCTCGCCAACTGTACTACAACTGTCAACTGTGCACGCACCCCGGGGCAACTGTATTTCAACTGTCCCTGGCCACCATCTACAACTGTCAACTGTACAACTGTCCAACTGTCAACTGTGCAACTGTCAACATCAACTGTCAACTGTCCCAACTGTTCAACTGTACCCACAACTGTCAACTGTGGTTCAACTGTGGTCAACTGTTCAACTGTTCCAACTGTCGTCAACTGTCAACTGTTTCCATCAACTGTGGCAACTGTACAACTGTTCAGCAACTGTCAACTGTCAACTGTTCAACTGTCAACTGTCAACTGTCAACTGTTCAACTGTTGGTAAATCAACTGTTCTCCAACTGTACAACTGTCAACTGTGCTCAACTGTGGCAACTGTAGCGCAACTGTGCATTTGGTCTGTCGTTCCAACTGTGACAACTGTTTCCAACTGTCAACTGTGAGTGTCGTGCAACTGTCAACTGTCAACTGTCTCCCAACTGTCAACTGTCAACTGTAACAACTGTTGGCTGAGACCAACTGTCAACTGTGCAACTGTTCAACTGTGGCCAACTGTGGGCATTTGAATACAACTGTGTCAGCCAACTGTACAACTGTCGAGCAACTGTTTTTGTGTCAACTGTGAAGCGTGGACAACTGTTTATATACAACTGTTGGCAACTGTCAACTGTGGGACAACTGTCCAACTGTTGCAACTGTCAACTGT"
t = "CAACTGTCA"

def findMotif(s,t):
    start = 0
    while True:
        start = s.find(t,start)
        if start == -1: return
        yield start + 1
        start += 1
        
x = findMotif(s,t)
answer = ''
for y in x:
    answer = answer + str(y) + " "

print(answer)
